# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

 desc "Submit a new debug Build to fabric Beta"
  lane :debugUpload do |values|

    parameter1  = values[:key]

    # build the debug variant
     build_android_app(task: "assembleDebug",properties: { 'versionCode' => parameter1 })


     # upload to Beta by Crashlytics
     crashlytics(
       # keys for organization: Super Dispatch
       api_token: "dd2a1abfbda79e1565ce023903b7823b006dfdbe",
       build_secret: "cba77e3c03be1b43c663d19a3784a2a8beeba43c2f63604755234a9489dee74c"
     )

  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
